parameters:
  extract_collection_name: raw
  fetch_limit: 1000
  load_collection_name: rag
  content_quality_score_threshold: 0.6
  retriever_type: parent
  embedding_model_id: text-embedding-3-small
  embedding_model_type: openai
  embedding_model_dim: 1536
  chunk_size: 640
  mock: false
  processing_batch_size: 8
  processing_max_workers: 4
  device: cpu # or cuda (for Nvidia GPUs) or mps (for Apple M1/M2/M3 chips)
